default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: spotify_new_releases_development

test:
  <<: *default
  database: spotify_new_releases_test

staging:
  <<: *default
  database: spotify_new_releases_staging

production:
  <<: *default
  database: spotify_new_releases_production
